CREATE DATABASE IF NOT EXISTS `phpframework`;
USE `phpframework`;
CREATE TABLE IF NOT EXISTS `tests`(
	id INT(10) UNSIGNED AUTO_INCREMENT,
	name CHAR(255) NOT NULL DEFAULT '',
	email CHAR(255) NOT NULL DEFAULT '',
	addr TEXT,
	add_time INT(10) UNSIGNED NOT NULL DEFAULT 0,
	ip INT(10) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
)ENGINE=myisam AUTO_INCREMENT=1 CHARSET=utf8;